name: MSBuild

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild Source -m

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
         name: MSBuild
         path: .
